import type { ItemDef } from '../../engine/types';

export const ITEMS: Record<string, ItemDef> = {
  coffee: {
    id: 'coffee',
    name: '新鲜咖啡',
    description: '一杯热气腾腾的黑咖啡。让你立刻清醒。',
    emoji: '☕',
    type: 'consumable',
    effects: { caffeine: 30, hp: 5 },
    functions: [
      {
        id: 'use',
        name: '喝下咖啡',
        description: '咖啡因 +30，生命 +5。适合在埋头苦干前使用。',
        action: 'use',
        timeCost: 3,
      },
    ],
  },
  stale_donut: {
    id: 'stale_donut',
    name: '变味甜甜圈',
    description: '昨天会议剩下的。还能吃。',
    emoji: '🍩',
    type: 'consumable',
    effects: { hp: 10 },
  },
  stress_ball: {
    id: 'stress_ball',
    name: '减压球',
    description: '捏紧它，帮你保持理智。',
    emoji: '🧘',
    type: 'consumable',
    effects: { hp: 25 },
    functions: [
      {
        id: 'use',
        name: '捏一捏',
        description: '生命 +25。Greg 的旧职场智慧暂时保护了你的精神状态。',
        action: 'use',
        timeCost: 2,
      },
    ],
  },
  energy_drink: {
    id: 'energy_drink',
    name: '功能饮料',
    description: '液体闪电。味道很差，效果很好。',
    emoji: '⚡',
    type: 'consumable',
    effects: { caffeine: 50, hp: -10 },
  },
  ergonomic_keyboard: {
    id: 'ergonomic_keyboard',
    name: '人体工学键盘',
    description: '花哨的分体键盘。你的手指会感谢你的。',
    emoji: '⌨️',
    type: 'equipment',
    effects: { productivity: 15 },
  },
  noise_cancelling_headphones: {
    id: 'noise_cancelling_headphones',
    name: '降噪耳机',
    description: '被祝福的宁静。开放式办公室再也伤害不了你了。',
    emoji: '🎧',
    type: 'equipment',
    effects: { productivity: 20, hp: 10 },
  },
  name_badge: {
    id: 'name_badge',
    name: '访客胸牌',
    description: '大楼的临时通行证。',
    emoji: '🪪',
    type: 'keyItem',
    effects: {},
    functions: [
      {
        id: 'access_rooftop',
        name: '进入天台',
        description: '可解锁前往天台的剧情选项。',
        timeCost: 0,
      },
      {
        id: 'karen_hint',
        name: 'Karen 的额外建议',
        description: 'Karen 在天台告诉你 Todd 明天有重要汇报，这会改变你对最终机会的判断。',
        timeCost: 0,
        unlockFlag: 'rooftop_karen',
        lockedDescription: '需要先在天台和 Karen 聊聊。',
      },
    ],
  },
  usb_drive: {
    id: 'usb_drive',
    name: '神秘 U 盘',
    description: '上面用马克笔写着"秘密"。',
    emoji: '💾',
    type: 'keyItem',
    effects: {},
    functions: [
      {
        id: 'inspect_label',
        name: '查看标签',
        description: '标签只写着"秘密"。Rick 显然不擅长信息安全命名。',
        timeCost: 1,
      },
      {
        id: 'read_org_chart',
        name: '读取旧组织架构图',
        description: '你读懂了旧组织架构图，知道哪些高管真正影响 Q3 战略。',
        timeCost: 15,
        unlockFlag: 'helped_rick',
        lockedDescription: '需要先帮 Rick 处理服务器，他才会告诉你 U 盘里哪些文件值得看。',
      },
    ],
  },
  sticky_notes: {
    id: 'sticky_notes',
    name: '便利贴',
    description: '一叠黄色便利贴。无限可能。',
    emoji: '📝',
    type: 'consumable',
    effects: { productivity: 5 },
    functions: [
      {
        id: 'use',
        name: '整理任务',
        description: '效率 +5。把混乱的第一天拆成几个还能处理的小任务。',
        action: 'use',
        timeCost: 5,
      },
    ],
  },
  office_plant: {
    id: 'office_plant',
    name: '桌面植物',
    description: '一株小多肉。在荧光灯下居然活了下来。',
    emoji: '🪴',
    type: 'equipment',
    effects: { hp: 10 },
  },
  snack_bar: {
    id: 'snack_bar',
    name: '能量棒',
    description: '还算健康。在休息室找到的。',
    emoji: '🥜',
    type: 'consumable',
    effects: { hp: 15 },
  },
};
