import type { GameMeta, HealthConfig, ProjectDef, StoryTimeConfig } from '../../engine/types';

export const workplaceTime: StoryTimeConfig = {
  defaultChapterId: 'chapter_1',
  chapters: {
    chapter_1: {
      id: 'chapter_1',
      name: '第一章：刚入职',
      startScene: 'onboarding',
      total: 40,
      enabled: false,
      unit: '小时',
      defaultActionTimeCost: 2,
      defaultItemTimeCost: 1,
    },
    chapter_2: {
      id: 'chapter_2',
      name: '第二章：接手项目',
      startScene: 'chapter2_start',
      total: 40,
      enabled: true,
      timeoutScene: 'ending_bad_marginalized',
      timeoutText: '你把太多时间花在休息和闲聊上，项目窗口期过去了。主管把核心任务交给了别人。',
      passFlag: 'project_advanced',
      passScene: 'chapter3_start',
      passText: '时间到了，但项目已经按期交付。其他部门的人开始注意到你了。',
      unit: '小时',
      defaultActionTimeCost: 4,
      defaultItemTimeCost: 1,
    },
    chapter_3: {
      id: 'chapter_3',
      name: '第三章：跨部门合作',
      startScene: 'chapter3_start',
      total: 32,
      enabled: true,
      timeoutScene: 'ending_bad_marginalized',
      timeoutText: '跨部门项目迟迟没有推进，业务方和主管都失去了耐心，你被排除在核心合作之外。',
      passFlag: 'c3_project_advanced',
      passScene: 'chapter4_start',
      passText: '时间用尽，但联合项目已顺利收尾。你成为了团队里的老员工。',
      unit: '小时',
      defaultActionTimeCost: 4,
      defaultItemTimeCost: 1,
    },
    chapter_4: {
      id: 'chapter_4',
      name: '第四章：带新人',
      startScene: 'chapter4_start',
      total: 120,
      enabled: true,
      timeoutScene: 'ending_bad_backstab',
      timeoutText: '带新人期间你迟迟没有处理好冲突，问题被放大后反噬到了你身上。',
      passFlag: 'c4_project_advanced',
      passScene: 'chapter5_check',
      passText: '时间到了，但你扛住了带新人的压力。公司迎来了年底的绩效季。',
      unit: '小时',
      defaultActionTimeCost: 8,
      defaultItemTimeCost: 1,
    },
    chapter_5: {
      id: 'chapter_5',
      name: '第五章：经济危机',
      startScene: 'chapter5_check',
      total: 40,
      enabled: true,
      timeoutScene: 'ending_bad_health',
      timeoutText: '你在高压和拖延中耗尽了最后的精力，身体先撑不住了。',
      passFlag: 'chapter5_cleared',
      passScene: 'chapter6_start',
      passText: '时间到了，但你已经稳住了下属团队，可以进入最终谈判。',
      unit: '小时',
      defaultActionTimeCost: 4,
      defaultItemTimeCost: 1,
    },
    chapter_6: {
      id: 'chapter_6',
      name: '最终章：寻找出路',
      startScene: 'chapter6_start',
      total: 24,
      enabled: true,
      timeoutScene: 'chapter6_bankruptcy',
      timeoutText: '你在犹豫和观望中耗尽了谈判窗口。等你回过神来，破产管理人已经接管了整栋大楼。',
      unit: '小时',
      defaultActionTimeCost: 2,
      defaultItemTimeCost: 1,
    },
    extra_industry_event: {
      id: 'extra_industry_event',
      name: '番外篇：行业活动',
      startScene: 'extra_industry_event_start',
      total: 8,
      enabled: true,
      timeoutScene: 'c6_settlement',
      timeoutText: '你在行业活动里耗了一整天，却没有建立任何有效连接。你收起工牌，回到街角咖啡馆重新思考下一步。',
      unit: '小时',
      defaultActionTimeCost: 2,
      defaultItemTimeCost: 1,
    },
  },
};

export const workplaceProjects: ProjectDef[] = [
  {
    id: 'chapter2_project',
    name: '接手项目',
    requiredHours: 16,
    completeFlag: 'project_advanced',
    workChoiceIds: ['work_on_project'],
    hubSceneIds: ['chapter2_hub'],
  },
  {
    id: 'chapter3_project',
    name: '联合项目',
    requiredHours: 20,
    completeFlag: 'c3_project_advanced',
    workChoiceIds: ['work_on_c3_project'],
    hubSceneIds: ['chapter3_hub'],
  },
  {
    id: 'chapter4_project',
    name: '补进度',
    requiredHours: 4,
    completeFlag: 'c4_project_advanced',
    workChoiceIds: ['work_on_c4_project'],
    hubSceneIds: ['c4_hub'],
  },
];

export const workplaceHealth: HealthConfig = {
  alertThreshold: 60,
  criticalThreshold: 20,
  criticalEndingScene: 'ending_bad_health',
  criticalNarrative: '连日的加班和高压让你突然感到一阵眩晕，你倒在了办公室里...',
  alertMessage: '⚠️ 健康警报：请注意休息！',
};

export const workplaceMeta: GameMeta = {
  title: '职场生存',
  subtitle: '刚入职篇',
  introLog: '你带着对未来的憧憬，踏入了这家知名大厂的大门。',
  characters: {
    boss: {
      id: 'boss',
      name: '主管',
      role: '你的直属上司',
      description: '掌握着你的绩效生杀大权，看重结果和服从度。',
      emoji: '🕴️',
    },
    hr_sister: {
      id: 'hr_sister',
      name: 'HR 姐姐',
      role: '行政与人事',
      description: '关心员工的身心状态，但也是公司制度的执行者。',
      emoji: '👩‍💼',
    },
    sales_bro: {
      id: 'sales_bro',
      name: '销售哥',
      role: '业务部门核心',
      description: '非常势利，只和有利用价值的人做朋友，消息灵通。',
      emoji: '🤑',
    },
    project_manager: {
      id: 'project_manager',
      name: '项目经理',
      role: '业务增长负责人',
      description: '非常关心业务指标，擅长把增长压力包装成“战略项目”。',
      emoji: '📈',
    },
    newbie_wang: {
      id: 'newbie_wang',
      name: '小王',
      role: '技术宅新人',
      description: '做事冲动，容易闯祸，但心思单纯。',
      emoji: '🤓',
    },
    newbie_li: {
      id: 'newbie_li',
      name: '小李',
      role: '精明的新人',
      description: '嘴巴甜，很会来事，但不认真干活，擅长向上管理。',
      emoji: '😏',
    },
  },
  statLabels: {
    hp: '健康',
    productivity: '砖功',
    charisma: '羽翼',
    upwardManagement: '向上管理',
    caffeine: '咖啡因',
    hobby: '业余爱好',
    indieDev: '独立开发',
  },
  endings: {
    ending_bad_redline: { label: '结局：触碰红线', className: 'bad' },
    ending_bad_health: { label: '结局：积劳成疾', className: 'bad' },
    ending_bad_marginalized: { label: '结局：边缘化', className: 'bad' },
    ending_bad_backstab: { label: '结局：遭遇背刺', className: 'bad' },
    ending_bad_fired: { label: '结局：扫地出门', className: 'bad' },
    ending_good_next_job: { label: '结局：充满希望的下一站', className: 'good' },
    ending_good_indie: { label: '结局：独立开发者', className: 'good' },
    ending_good_hobby: { label: '结局：把爱好变主业', className: 'good' },
    ending_good_chapter5: { label: '结局：护住团队', className: 'good' },
  },
};
