import type { ItemDef } from '../../engine/types';

export const ITEMS: Record<string, ItemDef> = {
  mac: {
    id: 'mac',
    name: '公司配发的 Mac',
    description: '一台崭新的 MacBook Pro，是你搬砖的利器。',
    emoji: '💻',
    type: 'keyItem',
    quantityMode: 'global',
    effects: {},
    functions: [
      {
        id: 'remote_work',
        name: '远程办公',
        description: '连上 VPN，随时随地开始搬砖。',
        unlockFlag: 'chapter2_started',
        lockedDescription: '需要接手项目后才能使用。',
      },
      {
        id: 'server_connect',
        name: '连接服务器',
        description: 'SSH 直连生产环境，心跳加速。',
        unlockFlag: 'chapter2_started',
        lockedDescription: '需要接手项目后才能使用。',
      },
      {
        id: 'model_training',
        name: '模型训练',
        description: '风扇狂转，GPU 满载。',
        unlockFlag: 'project_advanced',
        lockedDescription: '项目推进到一定阶段后解锁。',
      },
      {
        id: 'indie_dev',
        name: '独立开发',
        description: '在上班时间偷偷写自己的 App。',
        unlockFlag: 'chapter3_started',
        lockedDescription: '需要度过新手期才能解锁。',
      },
    ],
  },
  badge: {
    id: 'badge',
    name: '工牌',
    description: '你的身份象征，进出办公室和食堂全靠它。',
    emoji: '🪪',
    type: 'keyItem',
    quantityMode: 'global',
    effects: {},
  },
  snack: {
    id: 'snack',
    name: '办公室零食',
    description: '高糖高热量，能快速补充能量，但吃多了对身体不好。',
    emoji: '🍫',
    type: 'consumable',
    quantityMode: 'countable',
    effects: { hp: -5, productivity: 5 },
  },
  coffee: {
    id: 'coffee',
    name: '冰美式',
    description: '打工人的续命水。',
    emoji: '☕',
    type: 'consumable',
    quantityMode: 'countable',
    effects: { caffeine: 10, productivity: 10 },
  },
  water: {
    id: 'water',
    name: '温开水',
    description: '最朴实无华的饮品，养生必备。',
    emoji: '💧',
    type: 'consumable',
    quantityMode: 'countable',
    effects: { hp: 5 },
  },
};
